services:
  app-web:
    image: ${APP_IMAGE}
    container_name: ${APP_CONTAINER_NAME}
    pull_policy: never
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    environment:
      TZ: ${TZ:-Asia/Shanghai}
    ports:
      - "${APP_PORT}:80"
